<!-- Generated by xAI Grok (model: gpt-5.4) during provisioning. Edit freely. -->
<script setup lang="ts">
const config = useRuntimeConfig()
const appName = config.public.appName || 'Narduk Charts'
const siteUrl = config.public.appUrl || 'https://charts.nard.uk'
const pageTitle = `${appName} — Beautiful Vue charts for modern products`
const pageDescription = 'Build polished dashboards and data-rich interfaces with a charting library designed for Vue teams that care about clarity, speed, and visual quality.'

useSeo({
  title: pageTitle,
  description: pageDescription,
  ogImage: {
    title: pageTitle,
  },
})

useWebPageSchema({
  name: pageTitle,
  description: pageDescription,
})

const { data } = await useAsyncData('landing-page', async () => ({
  nav: [
    { label: 'Features', to: '#features', icon: 'i-lucide-layout-grid' },
    { label: 'Why Charts', to: '#why', icon: 'i-lucide-line-chart' },
    { label: 'Get Started', to: '#cta', icon: 'i-lucide-rocket' },
  ],
  stats: [
    { label: 'Vue-first API', value: 'Composable' },
    { label: 'Designed for', value: 'Dashboards' },
    { label: 'Focus', value: 'Clarity' },
  ],
  features: [
    {
      icon: 'i-lucide-line-chart',
      title: 'Readable by default',
      description: 'Thoughtful defaults help your charts feel clean, balanced, and presentation-ready from the first render.',
    },
    {
      icon: 'i-lucide-component',
      title: 'Built for Vue workflows',
      description: 'Compose charts naturally inside Nuxt and Vue apps with patterns that feel native to the ecosystem.',
    },
    {
      icon: 'i-lucide-gauge',
      title: 'Fast interaction',
      description: 'Smooth updates and responsive rendering keep dashboards snappy as your data changes in real time.',
    },
    {
      icon: 'i-lucide-palette',
      title: 'Themeable visuals',
      description: 'Create branded chart experiences with flexible styling that works across light and dark interfaces.',
    },
    {
      icon: 'i-lucide-scan-search',
      title: 'Data clarity first',
      description: 'Highlight trends, comparisons, and anomalies without burying users under visual noise.',
    },
    {
      icon: 'i-lucide-layers-3',
      title: 'Production-ready foundation',
      description: 'A strong base for analytics surfaces, internal tools, and customer-facing reporting products.',
    },
  ],
}))
</script>

<template>
  <div class="min-h-screen text-default">
    <UContainer class="py-4 sm:py-6">
      <div class="chart-glow flex items-center justify-between gap-4 rounded-2xl border border-white/40 bg-white/70 px-4 py-3 backdrop-blur dark:border-white/10 dark:bg-white/5">
        <div class="flex items-center gap-3">
          <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary ring-1 ring-primary/20">
            <UIcon name="i-lucide-chart-column-big" class="h-5 w-5" />
          </div>
          <div>
            <p class="text-sm font-semibold tracking-wide text-highlighted">
              {{ appName }}
            </p>
            <p class="text-xs text-muted">
              Vue charts for modern interfaces
            </p>
          </div>
        </div>

        <div class="hidden md:block">
          <UNavigationMenu :items="data?.nav || []" orientation="horizontal" />
        </div>
      </div>
    </UContainer>

    <main>
      <section class="relative overflow-hidden">
        <UContainer class="relative py-10 sm:py-14 lg:py-20">
          <div class="absolute inset-x-4 top-6 -z-10 h-[26rem] rounded-[2rem] border border-white/40 chart-grid" style="background: var(--gradient-chart-hero);" />

          <div class="grid items-center gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:gap-14">
            <div class="space-y-6">
              <UBadge color="primary" variant="subtle" class="rounded-full px-3 py-1">
                Crafted for dashboards, analytics, and product teams
              </UBadge>

              <div class="space-y-4">
                <h1 class="max-w-3xl text-4xl font-semibold tracking-tight text-highlighted sm:text-5xl lg:text-6xl">
                  Charts that feel as polished as the product around them.
                </h1>
                <p class="max-w-2xl text-base leading-7 text-muted sm:text-lg">
                  Narduk Charts helps Vue teams ship data visualizations that are expressive, usable, and visually refined without fighting the framework.
                </p>
              </div>

              <div class="flex flex-col gap-3 sm:flex-row">
                <UButton to="#cta" size="xl" color="primary" trailing-icon="i-lucide-arrow-right">
                  Explore the library
                </UButton>
                <UButton :to="siteUrl" size="xl" color="neutral" variant="soft" icon="i-lucide-globe">
                  Visit {{ siteUrl.replace('https://', '') }}
                </UButton>
              </div>

              <div class="grid max-w-2xl grid-cols-1 gap-3 pt-2 sm:grid-cols-3">
                <UCard
                  v-for="stat in data?.stats"
                  :key="stat.label"
                  class="chart-card border-white/50 bg-white/75 dark:border-white/10 dark:bg-white/5"
                >
                  <div class="space-y-1">
                    <p class="text-xs uppercase tracking-[0.18em] text-muted">
                      {{ stat.label }}
                    </p>
                    <p class="text-lg font-semibold text-highlighted">
                      {{ stat.value }}
                    </p>
                  </div>
                </UCard>
              </div>
            </div>

            <div class="relative">
              <UCard class="chart-glow overflow-hidden border-white/50 bg-white/80 dark:border-white/10 dark:bg-white/5">
                <div class="space-y-6 p-1">
                  <div class="flex items-center justify-between gap-4">
                    <div>
                      <p class="text-sm font-medium text-highlighted">
                        Revenue trend
                      </p>
                      <p class="text-xs text-muted">
                        Example product analytics view
                      </p>
                    </div>
                    <UBadge color="success" variant="subtle" icon="i-lucide-trending-up">
                      +18.4%
                    </UBadge>
                  </div>

                  <div class="rounded-2xl border border-white/50 bg-gradient-to-br from-primary/10 via-info/10 to-transparent p-4 dark:border-white/10">
                    <div class="flex h-56 items-end gap-3 sm:h-64">
                      <div class="flex h-full w-full items-end gap-3">
                        <div class="w-full rounded-t-xl bg-primary/25" style="height: 34%" />
                        <div class="w-full rounded-t-xl bg-primary/35" style="height: 48%" />
                        <div class="w-full rounded-t-xl bg-info/40" style="height: 42%" />
                        <div class="w-full rounded-t-xl bg-primary/50" style="height: 66%" />
                        <div class="w-full rounded-t-xl bg-info/50" style="height: 58%" />
                        <div class="w-full rounded-t-xl bg-primary" style="height: 82%" />
                        <div class="w-full rounded-t-xl bg-info" style="height: 74%" />
                      </div>
                    </div>
                  </div>

                  <div class="grid grid-cols-3 gap-3">
                    <div class="rounded-xl border border-white/50 p-3 dark:border-white/10">
                      <p class="text-xs text-muted">Series</p>
                      <p class="mt-1 font-semibold text-highlighted">Multi-axis</p>
                    </div>
                    <div class="rounded-xl border border-white/50 p-3 dark:border-white/10">
                      <p class="text-xs text-muted">Tooltips</p>
                      <p class="mt-1 font-semibold text-highlighted">Interactive</p>
                    </div>
                    <div class="rounded-xl border border-white/50 p-3 dark:border-white/10">
                      <p class="text-xs text-muted">Themes</p>
                      <p class="mt-1 font-semibold text-highlighted">Adaptive</p>
                    </div>
                  </div>
                </div>
              </UCard>
            </div>
          </div>
        </UContainer>
      </section>

      <section id="why" class="py-8 sm:py-12">
        <UContainer>
          <UCard class="chart-card border-white/50 bg-white/75 dark:border-white/10 dark:bg-white/5">
            <div class="grid gap-6 p-1 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
              <div class="space-y-3">
                <UBadge color="secondary" variant="subtle" class="rounded-full px-3 py-1">
                  Product framing
                </UBadge>
                <h2 class="text-2xl font-semibold tracking-tight text-highlighted sm:text-3xl">
                  Designed for teams who want insight, not chart clutter.
                </h2>
              </div>
              <div class="space-y-4 text-sm leading-7 text-muted sm:text-base">
                <p>
                  Great charts do more than render data. They guide attention, support decisions, and fit naturally into the product experience. Narduk Charts is shaped around that idea.
                </p>
                <p>
                  Whether you are building an internal analytics tool or a customer-facing reporting surface, the goal is the same: make important trends obvious and interactions feel effortless.
                </p>
              </div>
            </div>
          </UCard>
        </UContainer>
      </section>

      <section id="features" class="py-8 sm:py-12 lg:py-16">
        <UContainer>
          <div class="mb-8 flex flex-col gap-3 sm:mb-10">
            <UBadge color="info" variant="subtle" class="w-fit rounded-full px-3 py-1">
              Feature highlights
            </UBadge>
            <h2 class="text-2xl font-semibold tracking-tight text-highlighted sm:text-3xl lg:text-4xl">
              Everything you need to build confident data experiences.
            </h2>
            <p class="max-w-2xl text-sm leading-7 text-muted sm:text-base">
              A focused foundation for shipping charts that look sharp, perform well, and integrate cleanly into Vue applications.
            </p>
          </div>

          <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
            <UCard
              v-for="feature in data?.features"
              :key="feature.title"
              class="chart-card h-full border-white/50 bg-white/80 dark:border-white/10 dark:bg-white/5"
            >
              <div class="space-y-4 p-1">
                <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary ring-1 ring-primary/20">
                  <UIcon :name="feature.icon" class="h-6 w-6" />
                </div>
                <div class="space-y-2">
                  <h3 class="text-lg font-semibold text-highlighted">
                    {{ feature.title }}
                  </h3>
                  <p class="text-sm leading-6 text-muted">
                    {{ feature.description }}
                  </p>
                </div>
              </div>
            </UCard>
          </div>
        </UContainer>
      </section>

      <section class="py-6 sm:py-10">
        <UContainer>
          <USeparator />
        </UContainer>
      </section>

      <section id="cta" class="pb-16 pt-4 sm:pb-24">
        <UContainer>
          <UCard class="chart-glow overflow-hidden border-primary/20 bg-gradient-to-br from-primary/10 via-white/80 to-info/10 dark:from-primary/10 dark:via-white/5 dark:to-info/10">
            <div class="grid gap-6 p-2 sm:p-4 lg:grid-cols-[1fr_auto] lg:items-center">
              <div class="space-y-3">
                <UBadge color="primary" variant="subtle" class="rounded-full px-3 py-1">
                  Ready to build better charting UI?
                </UBadge>
                <h2 class="text-2xl font-semibold tracking-tight text-highlighted sm:text-3xl">
                  Start with a chart library that respects both your data and your design system.
                </h2>
                <p class="max-w-2xl text-sm leading-7 text-muted sm:text-base">
                  Discover a cleaner approach to Vue charting and create dashboards that users can understand at a glance.
                </p>
              </div>

              <div class="flex flex-col gap-3 sm:flex-row lg:flex-col">
                <UButton :to="siteUrl" size="xl" color="primary" trailing-icon="i-lucide-arrow-up-right">
                  Open charts.nard.uk
                </UButton>
                <UButton to="#features" size="xl" color="neutral" variant="soft" icon="i-lucide-sparkles">
                  Review features
                </UButton>
              </div>
            </div>
          </UCard>
        </UContainer>
      </section>
    </main>
  </div>
</template>
